Completed route for GET photos on /api/home/:id/photos
thefabfour/photo-carousel-service pull request #2
Opened 2021-01-16 23:43 UTC by kcords

Ready for review

2021-01-16 23:50 UTC, kcords commented
![](https://github.trello.services/images/mini-trello-icon.png) [Create routes for API requests](https://trello.com/c/ogL1bJ1Z/13-create-routes-for-api-requests)

2021-01-17 00:17 UTC, juanoxmar requested changes
Only one thing.

2021-01-17 00:17 UTC, juanoxmar commented on public/bundle.js
> +/******/ 	"use strict";
add your bundle.js to your .gitignore

2021-01-17 00:33 UTC, apat2010 reviewed
Looks great!

2021-01-17 00:40 UTC, kcords commented on public/bundle.js
> +/******/ 	"use strict";
bundle.js has been added to gitignore.

2021-01-17 00:49 UTC, apat2010 approved these changes
Reviewed! Looks clean and addressed Juan's concern

2021-01-17 01:32 UTC, merged